### ISSUE TITLE
Scaling content shows wrong levels

### ISSUE THREAD

**Issue by ssateneth** [kesava-wow/kuinameplates#100]
I've noticed that nameplates show the wrong level when you are in scaling content. This goes for low level battleground and legion invasions as far as I've seen (have not yet checked timewalking). Like if you are in battlegrounds, your team may be filled with level 41, 48, 47, 44 characters, but they are all scaled up to 49. And in invasions, all units (except a few bugged ones) are scaled to your level, or maybe 1 or 2 levels higher than you.

This is probably because you are not yet using UnitEffectiveLevel. UnitEffectiveLevel(target) returns the scaled level of the unit of interest. Might be useful to start using this instead of UnitLevel

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates2/commit/f0ad74e012b5d12d0bbf74cc669a4f4b9de53241
