### ISSUE TITLE
Aura error - version 248

### ISSUE THREAD

**Issue by ceylina** [kesava-wow/kuinameplates#18]
I was fighting a disturbed podling in the garrison when this error popped up while playing my survival hunter.

Message: Interface\AddOns\Kui_Nameplates_Auras\auras.lua:301: attempt to compare nil with number
Time: 02/25/15 11:46:02
Count: 4
Stack: Interface\AddOns\Kui_Nameplates_Auras\auras.lua:301: in function `DisplayAura'
Interface\AddOns\Kui_Nameplates_Auras\auras.lua:442: in function `?'
...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...s\AckisRecipeList\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...s\AckisRecipeList\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by kesava-wow** [comment]
Should be fixed by a501a6c563b91a59fe850e2a8a70d46b245efe10
