### ISSUE TITLE
Turns nameplates off?

### ISSUE THREAD

**Issue by jeffy162** [kesava-wow/kuinameplates#19]
I had this problem with Tidyplates, and installed this addon to stop it. It did until February 24th when 6.1 hit. Then this addon started doing it. The nameplates are on enemies only, and they are on like that all the time. Target an enemy and it's ok, kill the enemy and the nameplates turn off. You can check in the Blizzard options and they're off. Turn them on and go kill another mob, and they're off. After you kill the mob you can't tell until you go for another kill and realize you're too close (I'm a hunter). Check the Blizz options and they're off again. The only key that is bound that is near the "V" key is the "B" key for bags. You're not going to be opening your bags if you're in combat. There's no error, either.

**Comment by kesava-wow** [comment]
Do you perhaps have the option "Auto toggle in combat" checked under /knp > general? That option does this.

**Comment by jeffy162** [comment]
YES. DOH! I had that option checked when I started the game just now. Unchecked it and it made no difference. So, I exited the game and deleted the knp SavedVariables. THEN I remembered I could have just reloaded my UI. DOH (slaps self in head)! Works right now. Thank you very much.
