### ISSUE TITLE
Addon crash error

### ISSUE THREAD

**Issue by andrewhmtu** [kesava-wow/kuinameplates#24]
Hi, I posted this on the curse page as well, but got this error.

1x [ADDON_ACTION_BLOCKED] AddOn 'Kui_SpellList_Config' tried to call the protected function 'CompactRaidFrame17:Show()'.
!BugGrabber\BugGrabber.lua:589: in function <!BugGrabber\BugGrabber.lua:589>
[C]: in function `Show'
FrameXML\CompactUnitFrame.lua:290: in function `CompactUnitFrame_UpdateVisible'
FrameXML\CompactUnitFrame.lua:248: in function `CompactUnitFrame_UpdateAll'
FrameXML\CompactUnitFrame.lua:100: in function <FrameXML\CompactUnitFrame.lua:47>

Locals:

**Comment by kesava-wow** [comment]
I see this from a lot of unrelated addons. None of them (including mine) call the function this is yelling at me for calling. So I'm relatively certain it's a Blizzard issue, and it's been around for a while.
