### ISSUE TITLE
Neutral health bars showing green instead of yellow

### ISSUE THREAD

**Issue by F-I-R-E-F-O-X** [kesava-wow/kuinameplates#25]
![Issue](http://puu.sh/h8tBI/afb579a432.png)

**Comment by kesava-wow** [comment]
Not seeing this myself. Have you tried using a new/blank profile?

**Comment by F-I-R-E-F-O-X** [comment]
No difference with a new knp profile. Not that these are neutral reputation npcs, not wild / naturally attack-able ones.

**Comment by kesava-wow** [comment]
Ah. Thanks.

**Comment by kesava-wow** [comment]
After checking I've re-discovered that this is the behaviour with the default nameplates and that reputation information isn't available for nameplates until you mouseover or target the unit. I'm not currently interested in implementing a workaround for that.

**Comment by F-I-R-E-F-O-X** [comment]
Just had an idea on this. If you cached the reputation state after mouseover you would not need to worry about coloring being off every time. Though I have no idea how hard that would be to implement in code. :o
