### ISSUE TITLE
My HUGE ASS request / suggestion list <3

### ISSUE THREAD

**Issue by F-I-R-E-F-O-X** [kesava-wow/kuinameplates#26]
Okay currently KuiNameplates is the best addon of its type hands down. I think with a few additions it could be unbeatable.

~~1. Ability to manually whitelist / blacklist mobs (by name or type) as trivial~~
~~2. Mark pets as trivial~~
~~3. Flag companions / self for nameplate rendoring~~
4. Non combat rendoring that removes health bars and adds in <Guild> or '45 Humanoid' for a cleaner screen and more consistency
5. Different color for guildies (I would set mine to purple :P) 
6. Auto toggle in combat for all plates, not just hostile.
~~7. Bar offsetting for mobs that are so tall that their health bars go above the screen.~~
8. Attach quest icon to nameplate (Not sure if this is possible or not, but it would make things a hell of a lot cleaner)
9. Ability to edit glow size / texture

**Comment by kesava-wow** [comment]
1 & 2. I could change the sizes of the visible frames but the click boxes and boxes used to calculate how the nameplates intersect/overlap/stack would remain the same.
3. Not possible with an addon.
4. This is something I plan to explore.
5. Good idea. Possible for an external module.
6. Yes.
7. Not possible for an addon.
8. Vaguely possible but difficult. Check out QuestPlates. It /might/ be compatible with kui. Maybe.
9. Glow size can be edited pretty easily in core.lua (bgOffset) or with a custom.lua. Texture's a bit more fiddly as I don't use a standard backdrop texture for it (they were adding too much overhead).

**Comment by F-I-R-E-F-O-X** [comment]
On 1&2, how does it work currently? I was referring to the current implementation that you have.

**Comment by kesava-wow** [comment]
That functionality is built into the default nameplates - mobs which Blizzard flag as trivial have half-sized nameplates.

Nameplates don't have any official API built in to the game. Currently all we can really do is hide the default elements and show our own on top of it, in the same location, inheriting the same clickbox as the default nameplates. We can't create, resize or modify the clickable frames without breaking things when you enter combat.

**Comment by F-I-R-E-F-O-X** [comment]
Unfortunate! Still this is more of a visibility issue for me. In raids and other more active areas my screen becomes quite cluttered with health bars, Being able to differentiate becomes more important than odd clicking since in those scenarios trying to click is usually no longer an option anyway.

**Comment by F-I-R-E-F-O-X** [comment]
For 8, I was more referring to just having the '!' or '?' Icons somewhere as the hp bars tend to cover them. :P
Also I'm gunna go with not compatible on that one XD
