### ISSUE TITLE
251a2 Error Health Bar Text Offset

### ISSUE THREAD

**Issue by ceylina** [kesava-wow/kuinameplates#28]
This error happens every time when in the settings / text and trying to slide the "Health bar text offset

2x Kui_Nameplates\core.lua:336: deprecated function call: RegisterSize tex healthOffset 3
[C]: in function `error'
Kui_Nameplates\core.lua:336: in function `RegisterSize'
Kui_Nameplates\core.lua:378: in function `?'
Kui_Nameplates\config.lua:39: in function `ConfigChanged'
Kui_Nameplates\config.lua:91: in function <Kui_Nameplates\config.lua:80>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:794: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:614>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:851: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:839>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
Masque\Libs\AceGUI-3.0\AceGUI-3.0-34.lua:314: in function `Fire'
...sque\Libs\AceGUI-3.0-34\widgets\AceGUIWidget-Slider.lua:70: in function <...sque\Libs\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:60>

Locals:
nil

**Comment by kesava-wow** [comment]
Thanks!
