### ISSUE TITLE
251a2: Nameplate positioning incorrect when viewport geometry is changed

### ISSUE THREAD

**Issue by tzarc** [kesava-wow/kuinameplates#29]
I use the addon "CT_Viewport" to shrink my game area, giving me a slightly larger FoV and making sure I'm not rendering game content below other opaque UI elements.

After the recent batch of changes, with a smaller viewport configuration, the nameplate positioning is offset by a large vertical amount.

This is what it looks like with my normal viewport settings: http://i.imgur.com/NeFwkSL.jpg
This is what it looks like with no modified viewport geometry: http://i.imgur.com/vDEZ4Ku.jpg
For clarity, this is the layout with UI hidden: http://i.imgur.com/S4VKFJT.jpg

Obviously, this isn't limited to the test dummies, any other unit has the same issue. Ideally I'd like to get the positioning fixed - TidyPlates had the same problem and I switched to KNP because it wasn't similarly afflicted! (Please don't make me find another one *sadface*)

**Comment by kesava-wow** [comment]
You're using the beta (251a*), yes? Switch back to release. I'll fix this before 251 is stable.
Thanks!

**Comment by tzarc** [comment]
Yes, I am. Will do! Cheers.

**Comment by tzarc** [comment]
Just confirming everything is functional with the latest commit. Many thanks!
