### ISSUE TITLE
251a3 scale font size nil error

### ISSUE THREAD

**Issue by ceylina** [kesava-wow/kuinameplates#30]
Error happens even after reloading UI

17x Kui_Nameplates\core.lua:354: attempt to call method 'ScaleFontSizes' (a nil value)
Kui_Nameplates\core.lua:354: in function `?'
Kui_Nameplates\config.lua:41: in function `ConfigChanged'
Kui_Nameplates\config.lua:117: in function <Kui_Nameplates\config.lua:106>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:794: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:614>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:851: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:839>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
Masque\Libs\AceGUI-3.0\AceGUI-3.0-34.lua:314: in function `Fire'
...sque\Libs\AceGUI-3.0-34\widgets\AceGUIWidget-Slider.lua:70: in function <...sque\Libs\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:60>

Locals:
nil

**Comment by ceylina** [comment]
To add, I can change the font scaling but will get the lua error. Once I click ok and reload the UI, the settings will take effect. So it seems to be applying the settings but it throws this error.

**Comment by kesava-wow** [comment]
Easy fix. Thanks again!
