### ISSUE TITLE
Request for Totem / Pet Icons

### ISSUE THREAD

**Issue by Tonyleila** [kesava-wow/kuinameplates#31]
1. I woud like to have Big Icons ontop of the Totems
2. Icons for important pets. Only for the main pet so that its easy to see them between the pets from Ghoul army or Stampede.
3. Also woud like to make this army/stempede pet nameplates smaller or give them a different color so that you can still see the DKs red nameplate between all the other red plates.

**Comment by kesava-wow** [comment]
Issues should be atomic. I'll probably be closing this to seperate it out into three distinct issues when I next curate my issue list. Though I wouldn't mind if you did that yourself.
