### ISSUE TITLE
position looks weird

### ISSUE THREAD

**Issue by solor** [kesava-wow/kuinameplates#32]
![wowscrnshot_042015_165429](https://cloud.githubusercontent.com/assets/156806/7238512/88496994-e7d5-11e4-9539-8b2eecb8e804.jpg)

**Comment by kesava-wow** [comment]
Did you change the frame size in /knp without reloading UI and do you have fix aliasing on or off?

**Comment by solor** [comment]
DID NOT change the frame size
fix aliasing ON
all I did was change texture, change font, adjust font size to 0.76, and reloadUI

![1](https://cloud.githubusercontent.com/assets/156806/7240177/c8d38f56-e7e1-11e4-853e-5f02c4106e10.jpg)

**Comment by kesava-wow** [comment]
I can't reproduce this and I haven't heard it from anyone else.
Obviously it shouldn't be doing it either way, but does it work if you disable fix aliasing? (Don't worry, since the latest update it won't look as terrible without fixaa on)

**Comment by solor** [comment]
looks like a random case, I will gather more information.
