### ISSUE TITLE
Some Dots missing!

### ISSUE THREAD

**Issue by traxuz** [kesava-wow/kuinameplates#33]
I cant see Necrotic Plague from my dk and Flamestrike from my mage over the nameplates... i dont wanna change nameplates cause i like kui nameplates so much^^ plz help

**Comment by kesava-wow** [comment]
You can use KSLC [http://www.curse.com/addons/wow/kuispelllistconfig] to customise the whitelist used by auras. Alternatively you can turn the whitelist off entirely. I'll check those spells though.

**Comment by traxuz** [comment]
thx dude

**Comment by kesava-wow** [comment]
fixed locally
