### ISSUE TITLE
Aura timers on secondary targets

### ISSUE THREAD

**Issue by tylerancell** [kesava-wow/kuinameplates#36]
Having an issue with aura timers not being displayed on secondary targets unless I mouse over them or tab target.  Is this intended behaviour, or am I having a conflict somewhere?  I don't see any options to configure secondary targets, so I'm not sure.

If I manually apply a debuff to each target, it works fine - but if I spread fire dots with ignite, or spread diseases with blood boil, or diseases automatically spread with necrotic plague, then the timer is missing until I tab target or mouse over.

I posted this at curse as well - not sure which you check more frequently, so feel free to remove either this or the curse post - whichever works for you.

Thanks!

**Comment by kesava-wow** [comment]
http://www.curse.com/addons/wow/kuinameplates#c613

**Comment by kesava-wow** [comment]
Improvements provided by 8c255e585721f888da7bca31539114a5e5c2260d
