### ISSUE TITLE
about font setting

### ISSUE THREAD

**Issue by solor** [kesava-wow/kuinameplates#39]
Can we have separate font options for name / castbar text / aura time?
Pixel font is really good for castbar text and aura time, but for name, we have to use Chinese font which is not pixel perfect.

**Comment by solor** [comment]
I mean on Chinese client :smile:

**Comment by kesava-wow** [comment]
This is a niche issue I'd prefer to leave to custom.lua modifications. It's extremely easy to do with a custom.lua.
