### ISSUE TITLE
KuiSpellListConfig Error

### ISSUE THREAD

**Issue by ceylina** [kesava-wow/kuinameplates#75]
When using SpellListConfig to block player buff auras on nameplates using hte text only on friendly nameplate option, the folllowing protected function error will happen

[ADDON_ACTION_BLOCKED] AddOn 'Kui_SpellList_Config' tried to call the protected function 'CompactPartyFrameMember1:Show()'.
[C]: in function `Show'
FrameXML\CompactUnitFrame.lua:290: in function `CompactUnitFrame_UpdateVisible'
FrameXML\CompactUnitFrame.lua:248: in function `CompactUnitFrame_UpdateAll'
FrameXML\CompactUnitFrame.lua:100: in function <FrameXML\CompactUnitFrame.lua:47>

So while having this installed and added and configured, it taints the unit frames. I don't have any other details on this just as I am in a party and the text only names show, this happens every time.

While it may be possible that SpellListConfig is not the main culprit, removing the addon, removes the error.

I can run a taint log if need be but for now, I am disabling the addon as it is the root of my issue and I can live without text only friendly plates for now.

**Comment by ceylina** [comment]
Caught this running taintlooging

10/5 18:13:52.536  Execution tainted by Kui_SpellList_Config while reading LAST_ACTIVE_CHAT_EDIT_BOX - Interface\FrameXML\ChatFrame.lua:3841 ChatEdit_SetLastActiveWindow()
10/5 18:13:52.536      Interface\FrameXML\ChatFrame.lua:3776 ChatEdit_ActivateChat()
10/5 18:13:52.536      Interface\FrameXML\ChatFrame.lua:3420 ChatFrame_OpenChat()
10/5 18:13:52.536      OPENCHATSLASH:1
10/5 18:13:52.536  Execution tainted by Kui_SpellList_Config while reading LAST_ACTIVE_CHAT_EDIT_BOX - Interface\FrameXML\ChatFrame.lua:3842 ChatEdit_SetLastActiveWindow()
10/5 18:13:52.536      Interface\FrameXML\ChatFrame.lua:3776 ChatEdit_ActivateChat()
10/5 18:13:52.536      Interface\FrameXML\ChatFrame.lua:3420 ChatFrame_OpenChat()
10/5 18:13:52.536      OPENCHATSLASH:1
10/5 18:13:52.536  Execution tainted by Kui_SpellList_Config while reading LAST_ACTIVE_CHAT_EDIT_BOX - Interface\FrameXML\ChatFrame.lua:3842 ChatEdit_SetLastActiveWindow()
10/5 18:13:52.536      Interface\FrameXML\ChatFrame.lua:3776 ChatEdit_ActivateChat()
10/5 18:13:52.536      Interface\FrameXML\ChatFrame.lua:3420 ChatFrame_OpenChat()
10/5 18:13:52.536      OPENCHATSLASH:1
10/5 18:13:52.536  Execution tainted by Kui_SpellList_Config while reading LAST_ACTIVE_CHAT_EDIT_BOX - Interface\FrameXML\ChatFrame.lua:3842 ChatEdit_SetLastActiveWindow()
10/5 18:13:52.536      Interface\FrameXML\ChatFrame.lua:3776 ChatEdit_ActivateChat()
10/5 18:13:52.536      Interface\FrameXML\ChatFrame.lua:3420 ChatFrame_OpenChat()
10/5 18:13:52.536      OPENCHATSLASH:1

And this

10/5 18:24:44.808  Interface\FrameXML\LFGFrame.lua:2016 LFGCooldownCover_Update()
10/5 18:24:44.808  An action was blocked in combat because of taint from Kui_SpellList_Config - CompactPartyFrameMember1:Show()
10/5 18:24:44.808      Interface\FrameXML\CompactUnitFrame.lua:290 CompactUnitFrame_UpdateVisible()
10/5 18:24:44.808      Interface\FrameXML\CompactUnitFrame.lua:248 CompactUnitFrame_UpdateAll()
10/5 18:24:44.808      Interface\FrameXML\CompactUnitFrame.lua:50
10/5 18:24:44.808  Interface\FrameXML\LFGFrame.lua:2016 LFGCooldownCover_Update()
10/5 18:24:44.808  An action was blocked in combat because of taint from Kui_SpellList_Config - CompactPartyFrameMember2:Show()
10/5 18:24:44.808      Interface\FrameXML\CompactUnitFrame.lua:290 CompactUnitFrame_UpdateVisible()
10/5 18:24:44.808      Interface\FrameXML\CompactUnitFrame.lua:248 CompactUnitFrame_UpdateAll()
10/5 18:24:44.808      Interface\FrameXML\CompactUnitFrame.lua:50
10/5 18:24:44.808  Interface\FrameXML\LFGFrame.lua:2016 LFGCooldownCover_Update()
10/5 18:24:44.808  An action was blocked in combat because of taint from Kui_SpellList_Config - CompactPartyFrameMember3:Show()
10/5 18:24:44.808      Interface\FrameXML\CompactUnitFrame.lua:290 CompactUnitFrame_UpdateVisible()
10/5 18:24:44.808      Interface\FrameXML\CompactUnitFrame.lua:248 CompactUnitFrame_UpdateAll()
10/5 18:24:44.808      Interface\FrameXML\CompactUnitFrame.lua:50
10/5 18:24:44.808  Interface\FrameXML\LFGFrame.lua:2016 LFGCooldownCover_Update()
10/5 18:24:44.808  An action was blocked in combat because of taint from Kui_SpellList_Config - CompactPartyFrameMember4:Show()
10/5 18:24:44.808      Interface\FrameXML\CompactUnitFrame.lua:290 CompactUnitFrame_UpdateVisible()
10/5 18:24:44.808      Interface\FrameXML\CompactUnitFrame.lua:248 CompactUnitFrame_UpdateAll()
10/5 18:24:44.808      Interface\FrameXML\CompactUnitFrame.lua:50
10/5 18:24:44.808  Interface\FrameXML\LFGFrame.lua:2016 LFGCooldownCover_Update()
10/5 18:24:44.808  An action was blocked in combat because of taint from Kui_SpellList_Config - CompactPartyFrameMember5:Show()
10/5 18:24:44.808      Interface\FrameXML\CompactUnitFrame.lua:290 CompactUnitFrame_UpdateVisible()
10/5 18:24:44.808      Interface\FrameXML\CompactUnitFrame.lua:248 CompactUnitFrame_UpdateAll()
10/5 18:24:44.808      Interface\FrameXML\CompactUnitFrame.lua:50

**Comment by ceylina** [comment]
I can reproduce this indefinitely with only Kui nameplates (and the auras module) and kui SpellList config enabled

In nameplates settings
General Display / Combat Action friendly - set to Show Friendlies

Enable name-only display
Set Only show name of friendly units
check Even when damaged and Hide castbars
Enable SpellList config and have at least one buff disabled (not necessary but part of what I have. I have all castable buffs disabled)

Make sure to have a class that can summon a pet (dk,hunter, warlock, mage, monk)

Enter combat even against a training dummy

Call pet (this will spawn a pet frame in combat)

As soon as the pet is spawned and the pet frame enabled, the error will show every time

I recommend something like bugsack or buggrabber otherwise you will just get the "interface action failed because of an addon" message and not a lua error

Disabling kui spelllist config removes this error

**Comment by ceylina** [comment]
Here is my saved variables with the profile keys names removed for my own privacy

This contains both kuinameplates and kuispelllistconfig

http://pastebin.com/WBpeYqUP

**Comment by kesava-wow** [comment]
I don't actually call or interfere with any of the functions it's blaming me for tainting. I see this from various, unrelated addons and it never seems to actually cause any problems. It seems to be a Blizzard problem.

But I'll look into it at some point.

**Comment by RaphMad** [comment]
I can verify that KUI spelllist config is the source of the taint - ceylina already provided a complete environment to reproduce the problem.

Creeping taint problems are tricky to analyze - you call some function, taint it, that function calls something else, taints it, and so on.
The actual LUA errors only happen when some function that has been tainted that way attempts to call something protected (which may be a completely unrelated function and occur at a completely different time).

**Comment by kesava-wow** [comment]
Caused by use of UIDropDownMenu_Initialize

Will fix when I have a GPU.
