### ISSUE TITLE
Remove persistent buffs from Kui_Nameplates_Auras\lib\KuiSpellList\KuiSpellList.lua

### ISSUE THREAD

**Issue by ceylina** [kesava-wow/kuinameplates#76]
Since these persist so long as they are applied and the party/raid member does not die, it might be easier to remove them from the default spelllist and instead migrate them to spelllist config.

This are player buffs such as arcane brilliance, legacy of the white tiger, mark of the wild, etc.

Since these auras will show on all friendly nameplates, it can become cluttered in a large raid scenario. Unlike temporary buffs like aspect of the pack, the buffs stay for the duration of the raid or party so long as the player or unit are alive. 

I bring this up after having the issue on my monk using name only plates and having the monk buff show as an aura on all friendly nameplates. I tried to disable this but found the only way to do so is an additional addon. While using spellList config does remove the buff, it is an additional addon for one aura.

**Comment by Microstealer** [comment]
Personally I enjoy that feature but I understand the concern I would say dont remove the feature completely but make it an option in the settings to display or not display.

**Comment by kesava-wow** [comment]
You can either set up the time threshold under /knp > auras  to ignore long auras or manually ignore them with kuispelllistconfig, assuming you use the whitelist.
