### ISSUE TITLE
Display range

### ISSUE THREAD

**Issue by Microstealer** [kesava-wow/kuinameplates#77]
Hello love the addon has been a great replacement since tidy plates fell off and really appreciate someone made something new will be recommending it to others. The only thing I can think of to improve it that bothers me about it is the range you see the plates seems really short if its possible to increase how far in distance you will see the nameplate would be great. Besides that the addon is perfect meets all my needs and its very clean.

**Comment by Stanzilla** [comment]
That is nothing an addon can change.

**Comment by ceylina** [comment]
Use Range Display. It's a simple addon and that is all it does. The range of nameplates being drawn is controlled and protected by the game itself and no addon can increase that.

http://www.curse.com/addons/wow/range-display

**Comment by derickso** [comment]
TidyPlates can do this. I don't understand the answer.

**Comment by kesava-wow** [comment]
TidyPlates can't alter the render distance of nameplates, no addon can (not until legion, anyway). I'm pretty sure the auto-combat-toggling isn't enabled by default, but if it is, it's a bit late to fix that now anyway.
