### ISSUE TITLE
Threat module not active on old chars

### ISSUE THREAD

**Issue by Ision** [kesava-wow/kuinameplates#82]
Hello, so I got a really weird bug, the threat module just doesn't work at all  on my old chars (no red thingy on plates). It actually works perfectly when I created a new one today, which was the moment I discovered it actually existed.

Problem is I litterally tried everything (reseting confing char-wide, account-wide, with addons or no addons, deleting cache and such, changing blizzard settings and all). I just completely don't understand this bug at all since it works perfectly on my alt, and resetting all account settings changes absolutely nothing.
Hope you can help ^^

**Comment by Ision** [comment]
I forgot to mention I also tried to uninstall and reinstall the addon (and deleting all the saved config for it)

**Comment by Ision** [comment]
I actually did fix the bug. In order to do that, I had to install tidy plates again activate it, and get aggro (to actually seee if it worked). I had to do that on each character that played with tidy plates at any point in time (even 5 months ago).
Even if my issue is fixed I still would like if possible to know what did that and how to avoid it in the future.

**Comment by kesava-wow** [comment]
I imagine this is caused by the setting/CVar which enables threat on nameplates being disabled for some reason.

Or at least, I -think- that exists, and that would explains why activating TidyPlates would fix it.

I should be force-enabling it.

Thanks.
