### ISSUE TITLE
class pet/companion nameplates sometimes not shown

### ISSUE THREAD

**Issue by killarny** [kesava-wow/kuinameplates#84]
I haven't yet figured out what situations trigger this bug, but sometimes the class companions (hunter pets, warlock summons, etc) of **other players** do have their nameplate replaced by kui, other times they don't.

Also, (and maybe this is a different but related issue?) kui never seems to show a nameplate for **my** class companion pet/summon.

**Comment by kesava-wow** [comment]
When you say they don't get replaced by Kui, do you mean they show the default nameplates, or they don't display at all?

**Comment by killarny** [comment]
They don't display a nameplate at all - it uses the simple floating text style. Here's an example of an unstyled companion (although, in this case, it's a regular pet, not a class companion):

![unstyled companion](http://i.imgur.com/CpN8dZQ.png)

I suspect there is no API for those kinds of companions, since I've never seen any nameplate addon that was able to style them, so I'm not reporting that. It's just an example of what I meant by sasying that the nameplate isn't shown. That person has a water elemental out that - in this case - is styled by kui. What I'm reporting is that sometimes those summons are **NOT** styled by kui, and get the floating text instead.

I'll try to post a screenshot showing what I'm talking about on a summoned class companion/pet the next time I see it.

**Comment by killarny** [comment]
Here's an example of my class summon not being styled (I am Leyana in this pic):

![mine](http://i.imgur.com/DXQD2W2.png)

**Comment by kesava-wow** [comment]
This is to do with your interface options. Have a look at the checkboxes under Esc > interface > names. They are character specific options, so that explains why they seem to change sometimes.

**Comment by killarny** [comment]
Sadly, I don't think that's the reason.. I've got everything checked already:

![settings](http://i.imgur.com/GRmDEOH.jpg)

You can see under the settings box, that my companion is still sans-nameplate. :cry:

**Comment by kesava-wow** [comment]
Well regardless, addons can't interact with the floating names. Only nameplates. If a particular thing isn't showing a nameplate (and all of those options are checked), it's because Blizzard has flagged them not to show nameplates. It might be to do with player level in this case.

**Comment by killarny** [comment]
I don't understand why another player's summoned companion would have a nameplate, but not mine, when I haven't changed anything in my settings.

Oh well, thanks for taking the time to respond. I love your addon! :)
