### ISSUE TITLE
Feature Request: Target Count

### ISSUE THREAD

**Issue by zbugrkx** [kesava-wow/kuinameplates#85]
Hi,

Similar to what can be found in a few other nameplates addons, i woud love to have a target count (something like at the top right [11] for example) on nameplates. As a raid leader this would be so useful.

Thanks for the consideration.

regards

BuG

**Comment by kesava-wow** [comment]
You'll need to explain what you mean or link to another addon which does it for me.

**Comment by zbugrkx** [comment]
I guess an image speaks better than words : http://imgur.com/n86HzjK

top right, you can see a counter which is the number of players currently targetting this mob.
