### ISSUE TITLE
Feature Request: PVP BG Healer icon

### ISSUE THREAD

**Issue by zbugrkx** [kesava-wow/kuinameplates#86]
Hi,

There used to be an old addon that would put a healer icon next to a healer nameplate in bgs. I was wondering if you would be able to do something similar to your nemesis quest and have a healer icon next an enemy in bgs. (very useful feature in rbgs for instance)

Thanks for the consideration

regards

BuG

**Comment by kesava-wow** [comment]
HealersHaveToDie can be used in conjunction with lip namespkalates to do this.. I have no p

**Comment by kesava-wow** [comment]
HealersHaveToDie can be used in conjuction with KuiNameplates to achieve this. I have no plan to write my own implementation of it.
