### ISSUE TITLE
1x [ADDON_ACTION_BLOCKED] Addon 'Kui_SpellList_Config' tried to call a protected function 'CompactRaidFrame17:Show()'.

### ISSUE THREAD

**Issue by brjake** [kesava-wow/kuinameplates#89]
"1x [ADDON_ACTION_BLOCKED] Addon 'Kui_SpellList_Config' tried to call a protected function 'CompactRaidFrame17:Show()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `Show'
FrameXML\CompactUnitFrame.lua:290: in function `CompactUnitFrame_UpdateVisible'
FrameXML\CompactUnitFrame.lua:248: in function `CompactUnitFrame_UpdateAll'
FrameXML\CompactUnitFrame.lua:100: in function <FrameXML\CompactUnitFrame.lua:47>

Locals:"

Google translater help me with this: "tried to call a protected function" D:

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates/issues/75
