### ISSUE TITLE
Feature Request: Giant Target Highlight

### ISSUE THREAD

**Issue by pfeifenheini** [kesava-wow/kuinameplates#93]
Hi,

I like your AddOn very much. But I miss one feature that caused me to stick to TidyPlates: Thread Plates even though its support stopped a long time ago. And that is to get an more than obvious highlight of the current target, without fading other targets away.

In ThreadPlates I was able to surround the nameplate of the current target with enormous white arrows. Like you can see on this screen:
![targethighlight](https://cloud.githubusercontent.com/assets/13488943/16989738/9af33660-4e95-11e6-9c32-983d7fd51adc.png)

It looks super ugly, I know, but it helps me so much. I would love to see something like that in your AddOn. Maybe something like the threat brackets with a different color.

Cheers!

**Comment by kesava-wow** [comment]
There were "target arrows" in the previous version, I'm still planning to put them back. It's just, they were really ugly. So I didn't yet.

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates2/issues/23
