### ISSUE TITLE
Aura timer text sometimes not showing or disappearing

### ISSUE THREAD

**Issue by leobolin** [kesava-wow/kuinameplates#96]
I've noticed this happening when multi-dotting a lot of targets rapidly, where the timer text will either never show, show much later or sometimes even disappear randomly after counting down for a while.

I'm not 100% sure what causes it, but often the text will not appear if I start casting Vampiric Touch on one target and then rapidly switching target before the cast is finished. Sometimes the timer shows, sometimes not, and sometimes I have to target the mob again and it will appear after several seconds.

Overall, timer text feels very inconsistent. Maybe there's some issue with how it is being updated?

**Comment by kesava-wow** [comment]
Caused by the time text threshold setting.

**Comment by leobolin** [comment]
> Caused by the time text threshold setting.

What, no? My timer threshold is set to -1 (always display the timer) and it happens **randomly**. I'm pretty sure it's a bug. Sometimes the text just disappears completely and then comes back 5 seconds later.

**Comment by kesava-wow** [comment]
You modified the code, yes? Can you reproduce it without your modifications?

**Comment by kesava-wow** [comment]
And in future if you modifiy code, point that out when you make bug reports.

**Comment by leobolin** [comment]
It is happening with a freshly downloaded version without any modifications.

**Comment by kesava-wow** [comment]
Ok, it was indeed cased by the timer_threshold setting, however it wasn't being restored correctly to your setting (-1) upon load. Fixed in the next version (https://github.com/kesava-wow/kuinameplates2/commit/0f4d30b0081cc13bb6792fa9efb3890e2f89095b). Thanks.

By the way, this is the "wrong" repo. https://github.com/kesava-wow/kuinameplates2/issues is the new one.

**Comment by leobolin** [comment]
Cool thanks. [Here is a video I took of the bug happening](https://www.youtube.com/watch?v=6Hw-jEX7m1g) (~22 seconds in and again ~52 seconds in) but I guess you were able to reproduce it yourself. Glad it's being fixed!

**Comment by leobolin** [comment]
Been playing around with the latest beta version for a while now and it seems fixed. Thank you so much! :D
